#
# Libor Novak
# 10/13/2016
#
# Config file for EOA image compression with the Hill Climber algorithm
#

####################################################################################################
#######################################  GLOBAL PARAMETERS  ########################################
####################################################################################################

# Image that will be approximated with the compression algorithm
path_image: "/Users/libornovak/Data/eoa_image_compression/images/mona_lisa_face.jpg"

# Path to the folder with output and approximaged image
path_out: "/Users/libornovak/Data/eoa_image_compression/results/20161024/mona_lisa_face/"

# Length of the chromozome, that will represent the image (number of shapes)
chromozome_length: 100

# Type of shape to be used in the chromozome
shape_type: 1  # 1 = Circle

# Which algorithm will be used for compression
algorithm: 1  # 1 = HillClimber


####################################################################################################
######################################  ALGORITHM PARAMETERS  ######################################
####################################################################################################

# Parameters of the Steepest Ascent Hill Climber algorithm
hill_climber:
    # Number of iterations (mutations) to be tried in one hill climb run
    num_iterations: 5000
    # Number of solutions to select from in each iteration
    pool_size: 10


# Mutator is a common structure, which takes care of mutating the chromozome and the shapes, which
# represent the image
mutator:
    # Probability of the whole shape being mutated at all
    shape_mutation_prob: 0.2

    # Probability that a color (the alpha) channel will be mutated
    color_mutation_prob: 0.2
    alpha_mutation_prob: 0.2
    # Standard deviation of the mutation for color and alpha channels
    color_mutation_stddev: 10
    alpha_mutation_stddev: 8

    # Probability of a position (point) being mutated
    position_mutation_prob: 0.2
    # Standard deviation of the position mutation
    position_mutation_stddev: 20
    # Probability of a position (point) being completely randomly reinitialized
    position_reinitialization_prob: 0.1

    # CIRCLE specific
    radius_mutation_prob: 0.2
    radius_mutation_sdtddev: 5

